"""Async Redis client provider.

We accept any object that quacks like ``redis.asyncio.Redis`` so tests can
inject ``fakeredis.aioredis.FakeRedis`` without code changes.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

import redis.asyncio as redis_async


@runtime_checkable
class AsyncRedisLike(Protocol):
    async def set(self, *args, **kwargs): ...
    async def get(self, *args, **kwargs): ...
    async def delete(self, *args, **kwargs): ...
    async def incr(self, *args, **kwargs): ...
    async def expire(self, *args, **kwargs): ...
    async def eval(self, *args, **kwargs): ...
    async def evalsha(self, *args, **kwargs): ...
    async def script_load(self, *args, **kwargs): ...
    async def zadd(self, *args, **kwargs): ...
    async def zremrangebyscore(self, *args, **kwargs): ...
    async def zcard(self, *args, **kwargs): ...
    async def sadd(self, *args, **kwargs): ...
    async def srem(self, *args, **kwargs): ...
    async def sismember(self, *args, **kwargs): ...
    async def hset(self, *args, **kwargs): ...
    async def hget(self, *args, **kwargs): ...
    async def aclose(self) -> None: ...


def create_redis(url: str) -> AsyncRedisLike:
    return redis_async.from_url(url, encoding="utf-8", decode_responses=True)
